from os import PathLike
from enum import Enum
from typing import Union, AnyStr
from typing_extensions import TypeAlias

PathType: TypeAlias = Union[AnyStr, PathLike]

class BinaryUnit(Enum):
    BIT = ...
    BYTE = ...
    KILO_BYTE = ...
    MEGA_BYTE = ...
    GIGA_BYTE = ...
    TRILLION_BYTE = ...
    PETA_BYTE = ...
    EXA_BYTE = ...
    ZETTA_BYTE = ...
    YOTTA_BYTE = ...
    BRONTO_BYTE = ...

def get_ext(path: PathType) -> str: ...

def get_filename(path: PathType) -> str: ...
