from typing import Tuple
from types import ModuleType

def str2tuple(version: str) -> Tuple[int | str]: ...

def tuple2str(version: Tuple[int | str]) -> str: ...

def leq(lhs: str, rhs: str): ...

def min_version(module: ModuleType, min_version_str: str = ""): ...

def exact_version(module: ModuleType, version_str: str = ""): ...
